### ISSUE TITLE
GCpedia link broken

### ISSUE THREAD

**Issue by fstarnaud** [canada-ca/cloud-guardrails-O365#241]
### Summary

GCpedia link broken.

### Steps to reproduce

Log on computer with GC network access (e.g. DRENET) and try to access link supplied in README.md:
https://www.gcpedia.gc.ca/gcwiki/images/0/0b/Office_365_Security_Baseline_Configuration.xlsx 

### Example

N/A

### What is the current *bug* behavior?

Not Found (404)
The requested URL was not found on this server.

### What is the expected *correct* behavior?

The Office_365_Security_Baseline_Configuration.xlsx file should be downloaded.

### Relevant logs and/or screenshots

N/A

### Possible fixes

Update the link, perhaps to https://www.gcpedia.gc.ca/gcwiki/SPIN_2017-01_Baseline_Security_Controls ?

**Comment by ptd-tbs** [comment]
Resolved via this PR - https://github.com/canada-ca/cloud-guardrails-O365/pull/213

**Comment by fstarnaud** [comment]
Good, however only the English link was corrected; the link in the French part below is still broken.
