### ISSUE TITLE
New Zealand Government M365 Team is seeking Contact with members of your team   

### ISSUE THREAD

**Issue by bbbri57** [canada-ca/cloud-guardrails-O365#90]
Hi there, I work for New Zealand Government. We are looking to provide a similar set of documents to what you have created to help our Government Agencies adopt cloud. Right now we are attempting to write a blueprint for M365 and are keen to talk to folks in your team about how they engaged directly with Microsoft.  You can contact me back @ brian.ransfield@dia.govt.nz 
Thanks and regards,
Brian

**Comment by ptd-tbs** [comment]
Hi Brian,

I will send you an email so we can discuss our approach in establishing the guardrails and baseline configuration.

Thanks,
Po
